blank_issues_enabled: false
contact_links:
  - name: Ask in Discussions
    url: https://github.com/nexesninja/raspberrypi-telegram-bot/discussions
    about: Ask questions and get help in Discussions.
